name: fft
description: A library for fourier transformations using the Cooley-Tukey algorithm
version: 0.2.0
author: Edouard Tavinor <edouardtavinor@gmail.com>
homepage: https://github.com/ehrt74/dart_lang_fft

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  my_complex:
    git:
      url: https://github.com/janipiippow/dart_my_complex.git
  tuple: ^2.0.0

dev_dependencies:
  test: '>=0.12.0 <2.0.0'